name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: build
            os: ubuntu-latest
          - target: iosX64Test
            os: macos-latest
          - target: macosX64Test
            os: macos-latest
          - target: tvosX64Test
            os: macos-latest
          - target: watchosX64Test
            os: macos-latest
          - target: mingwX64Test
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew ${{ matrix.target }}
